import { FormConstructorType } from '../../Types';

const formConstructor: Array<FormConstructorType> = [
  {
    id: 'title-exercise',
    label: 'Название',
    description: 'Укажите название упражнения',
    required: true,
    type: 'text',
    name: 'title',
  },
  {
    id: 'link-exercise',
    label: 'ID упражнения',
    description: 'Укажите идентификатор ключа ссылки упражнения',
    required: true,
    type: 'text',
    name: 'link',
  },
  {
    id: 'description-exercise',
    label: 'Описание',
    description: 'Укажите описание упражнения',
    required: true,
    type: 'text',
    name: 'action',
  },
  {
    id: 'count-repeat-exercise',
    label: 'Повторения',
    description: 'Укажите количество повторений упражнения',
    type: 'number',
    name: 'count_repeat',
    min: 1,
    value: 1,
  },
  {
    id: 'time-pause-exercise',
    label: 'Перерыв',
    description: 'Укажите время перерыва упражнения от 1 до 10 секунд',
    type: 'number',
    name: 'time_pause',
    min: 1,
    max: 10,
    value: 5,
  },
  {
    id: 'delay-exercise-exercise',
    label: 'Начальный перерыв',
    description: 'Укажите время перерыва до начала упражнения от 0 до 10 секунд',
    type: 'number',
    name: 'delay_exercise',
    min: 0,
    max: 10,
    value: 0,
  },
  {
    id: 'delta-time-exercise',
    label: 'Нарастание перерыва',
    description: 'Укажите коэффициент арифметической прогрессии перерыва упражнения от 0 до 10',
    type: 'number',
    name: 'delta_time',
    min: 0,
    max: 10,
    value: 0,
    step: 0.1,
  },
  {
    id: 'time-exercise',
    label: 'Время повторения',
    description: 'Укажите продолжительность выполнения упражнения от 1 секунды',
    type: 'number',
    name: 'time_progress',
    min: 1,
    value: 1,
  },
  {
    id: 'img-exercise',
    label: 'Название файла',
    description: 'Укажите путь до картинки упражнения',
    type: 'text',
    name: 'img',
    required: true,
  },
];

export default formConstructor;
